# Generated by Django 4.2.5 on 2023-09-28 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("positions", models.CharField(max_length=30)),
                ("salary", models.IntegerField(default=0)),
                ("students_alloted", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="courses_internships",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("company", models.CharField(max_length=30)),
                ("students_enrolled", models.IntegerField(default=0)),
                ("level", models.CharField(max_length=30)),
                ("durations", models.CharField(max_length=30)),
                ("grade", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("gender", models.CharField(max_length=4)),
                ("age", models.IntegerField(default=0)),
                ("branch", models.CharField(max_length=30)),
                ("semester", models.CharField(max_length=2)),
                ("divison", models.CharField(max_length=1)),
                ("address", models.CharField(max_length=30)),
                ("photo", models.ImageField(upload_to="")),
                ("reports", models.FileField(upload_to="reports")),
                ("certificates", models.FileField(upload_to="certificates")),
                ("internships", models.FileField(upload_to="internships")),
                ("grade", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.CharField(max_length=200)),
                ("reply", models.CharField(max_length=200)),
                ("created_at", models.DateField(max_length=30)),
                ("updated_at", models.DateField(default=0)),
                (
                    "info",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="myuser",
            name="info",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.info",
            ),
        ),
    ]
