# Generated by Django 4.2.5 on 2023-09-30 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="certificates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificates", models.FileField(upload_to="certificates")),
            ],
        ),
        migrations.CreateModel(
            name="internships",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("internships", models.FileField(upload_to="internships")),
            ],
        ),
        migrations.CreateModel(
            name="reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repots", models.FileField(upload_to="repots")),
            ],
        ),
        migrations.CreateModel(
            name="student_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("gender", models.CharField(max_length=4)),
                ("age", models.IntegerField(default=0)),
                ("branch", models.CharField(max_length=30)),
                ("semester", models.CharField(max_length=2)),
                ("divison", models.CharField(max_length=1)),
                ("address", models.CharField(max_length=30)),
                ("photo", models.ImageField(upload_to="")),
                ("grade", models.CharField(max_length=30)),
                (
                    "certificates",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.certificates",
                    ),
                ),
                (
                    "internships",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.internships",
                    ),
                ),
                (
                    "reports",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.reports",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="myuser",
            name="info",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.student_info",
            ),
        ),
        migrations.DeleteModel(
            name="info",
        ),
    ]
