# Generated by Django 4.2.5 on 2023-09-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rename_certificates_certificates_certificate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_info",
            name="photo",
            field=models.FileField(upload_to="profiles"),
        ),
    ]
