# Generated by Django 4.2.6 on 2023-10-16 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_certificate_certificate_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('domain', models.CharField(max_length=30)),
                ('applied', models.BooleanField(default=False)),
                ('key', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='domain',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='backlogs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
    ]
